# Generated by Django 2.1.5 on 2019-02-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190220_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='details',
            field=models.CharField(default='', max_length=150),
        ),
    ]
