# Generated by Django 2.1.5 on 2019-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190220_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
