# Generated by Django 2.1.5 on 2019-02-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tutor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instruments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='instruments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
