# Generated by Django 2.2a1 on 2019-02-26 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190226_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availablity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=8)),
                ('day_of_week', models.CharField(max_length=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='instruments',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Availablity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
        ),
        migrations.AddField(
            model_name='availablity',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hour'),
        ),
        migrations.AddField(
            model_name='availablity',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tutor'),
        ),
    ]
