# Generated by Django 2.1.5 on 2019-03-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='details',
        ),
        migrations.AddField(
            model_name='student',
            name='instruments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='instruments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
