# Generated by Django 2.1.5 on 2019-02-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190220_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='details',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
