# Generated by Django 2.1.5 on 2019-03-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_student_extra_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='availablity',
            new_name='availability',
        ),
        migrations.AlterField(
            model_name='hour',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10),
        ),
    ]
