# Generated by Django 2.1.5 on 2019-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190220_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='extra_pic',
            field=models.ImageField(default='concert.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='concert.jpg', upload_to='images/'),
        ),
    ]
