# Generated by Django 2.1.5 on 2019-03-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190303_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='student',
            name='second_inst',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='second_inst',
        ),
    ]
