# Generated by Django 2.1.5 on 2019-02-26 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190226_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availablity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availablity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Availablity')),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=8)),
                ('day_of_week', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='instrument_req',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='instrument_avail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='availablity',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Hour'),
        ),
        migrations.AddField(
            model_name='availablity',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tutor'),
        ),
    ]
