# Generated by Django 2.1.5 on 2019-03-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190226_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='instruments',
        ),
    ]
